# ./server/Dockerfile.dev

from mcr.microsoft.com/dotnet/sdk:8.0 AS dev
workdir /app

run apt-get update && apt-get install -y netcat-openbsd

# Copy project files
copy . .

# Restore dependencies
run dotnet restore

run dotnet new tool-manifest --force
run dotnet tool install dotnet-ef --version 9.0.9

# Expose HTTP port
expose 80

# Copy entrypoint script
copy entry-point.sh .

# Make entrypoint executable
run chmod +x entry-point.sh

# Expose HTTP port
expose 80

# Run entrypoint
cmd ["./entry-point.sh"]

# Start app using dotnet run
# cmd [ "dotnet", "run", "--urls=http://0.0.0.0:80" ]

