# ./server/Dockerfile.dev

from mcr.microsoft.com/dotnet/sdk:8.0 AS dev
workdir /app

# Copy project files
copy . .

# Restore dependencies
run dotnet restore

# Expose HTTP port
expose 80

# Start app using dotnet run
cmd [ "dotnet", "run", "--urls=http://0.0.0.0:80" ]

