services:
  database:
    image: postgres:15
    container_name: barter-database-dev
    environment:
      POSTGRES_DB: barter
      POSTGRES_USER: barter_user
      POSTGRES_PASSWORD: barter_password
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./database/database-initializers:/docker-entrypoint-initdb.d
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Username=barter_user;Password=barter_password;Database=barter
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build:
      context: ./view
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  data:

