development:
	docker compose --file development-compose.yml build --no-cache
	docker compose --file development-compose.yml up
production:
	docker compose --file development-compose.yml build --no-cache
	docker compose --file production-compose.yml up

