development:
	docker compose --file development-compose.yml build --no-cache backend
	docker compose --file development-compose.yml up
no-cache:
	docker compose --file development-compose.yml build --no-cache
	docker compose --file development-compose.yml up
production:
	docker compose --file production-compose.yml build --no-cache
	docker compose --file production-compose.yml up

